title: Cyrill Rafael Vasilyev
description: Artwork showcase
theme: null

url: www.cyrillrafael.com
# Permalinks
permalink: /:title/

# Navigation links
nav_links:
  - title: Paintings
    url: /paintings
  - title: Linocuts
    url: /linocuts
  - title: About
    url: /about
  - title: CùìáV
    url: /cv
  - title: Instagram
    url: https://www.instagram.com/cyrillrafael/
    icon: fab fa-instagram
  - title: Telegram
    url: https://t.me/+31686218199/
    icon: fab fa-telegram

# Redirects
redirects:
  - from: "/"
    to: "/paintings/"


paintings_data:
  - filename: my_dear_teacher.jpg
    dimensions: 220x120cm
  - filename: behind_red_door_sitting.jpg
    dimensions: 220x120cm
  - filename: 2018 untitled.jpg
    dimensions: 120x160cm
